server:
  port: 8092
spring:
  application:
    name: mentor-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mentor_service
    username: root
    password: root
  