server:
  port: 8091
spring:
  application:
    name: student-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/student_service
    username: root
    password: root
  