server:
  port: 8081
spring:
  application:
    name: admin-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/admin_service
    username: root
    password: root
  